[tasks.run]
alias = "r"
description = "Run dublette"
run = "cargo run --"

[tasks.test]
alias = "t"
description = "Run tests"
run = "cargo test"

[tools]
"cargo:convco" = "latest"
dprint = "latest"
hk = "latest"
pkl = "latest"
rust = "latest"
